[phases.setup]
nixPkgs = ["chromium", "nss", "nspr", "atk", "libdrm", "libX11", "libXcomposite", "libXdamage", "libXext", "libXrandr", "mesa", "pango", "cairo", "alsa-lib"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node server.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/run/current-system/sw/bin/chromium"
